[package]
name = "pow"
version = "0.1.2"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
description = """
Generate or verify sha256 based proofs of work over arbitrary typed data.
"""
edition = "2018"
documentation = "https://docs.rs/pow"
tags = ["proof of work", "pw set", "powtag", "tag"]
readme = "readme.md"
license = "MIT OR Apache-2.0"

[dependencies]
sha2 = "0.8.0"
serde = { version = "1", features = ["derive"] }
bincode = "1.1.3"
