[package]
name = "pow"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
description = """
Tag arbitrary data types with proof of work based on sha256.
"""
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
sha2 = "0.8.0"
serde = { version = "1", features = ["derive"] }
bincode = "1.1.3"
